server.port: 8761

spring:
    config.import: configserver:http://config_server:8888
    application.name: eureka-server

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
