version: "3.8"

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  postgres_keycloak:
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    restart: unless-stopped
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
#      - ./data:/var/lib/postgresql/data
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 100000000
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 250M
          cpus: '0.25'
    logging: *logging

  postgres_app:
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    restart: unless-stopped
    container_name: postgres_app
    environment:
      POSTGRES_DB: ${POSTGRES_APP_DB}
      POSTGRES_USER: ${POSTGRES_APP_USER}
      POSTGRES_PASSWORD: ${POSTGRES_APP_PASSWORD}
    volumes:
      #      - ./data:/var/lib/postgresql/data
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 100000000
      - ./docker/init:/docker-entrypoint-initdb.d
    expose:
      - 5432
    ports:
      - ${POSTGRES_APP_PORT}:5432
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 250M
          cpus: '0.25'
    logging: *logging

  keycloak:
    build:
      context: ./docker
      dockerfile: keycloak.Dockerfile
    container_name: keycloak
    command: ['start-dev', "--import-realm"]
    restart: unless-stopped
    environment:
      KC_DB: ${KC_DB}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL: ${KC_DB_URL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - ${KC_PORT}:8080
    volumes:
      - ./keycloak/demo-realm.json:/opt/keycloak/data/import/realm.json:ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 500M
          cpus: '1'
    logging: *logging
    depends_on:
      - postgres_keycloak

  zookeeper:
    build:
      context: ./docker
      dockerfile: zookeeper.Dockerfile
    container_name: zookeeper
    restart: on-failure
    ports:
      - ${ZOOKEEPER_PORT}:2181
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 250M
          cpus: '1'
    logging: *logging

  kafka:
    build:
      context: ./docker
      dockerfile: kafka.Dockerfile
    container_name: kafka
    hostname: kafka
    restart: on-failure
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:${KAFKA_PORT}
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:${KAFKA_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    logging: *logging
    depends_on:
      - zookeeper

  kafdrop:
    build:
      context: ./docker
      dockerfile: kafdrop.Dockerfile
    container_name: kafdrop
    restart: on-failure
    ports:
      - ${KAF_DROP_PORT}:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 250M
          cpus: '1'
    logging: *logging
    depends_on:
      - kafka

  discovery:
    build:
      context: ./eureka-server
      dockerfile: eureka-server.Dockerfile
    container_name: discovery
    restart: on-failure
    ports:
      - ${EUREKA_SERVER_PORT}:8761
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 250M
          cpus: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging: *logging
    depends_on:
      - kafka

  config_server:
    build:
      context: ./github-config-server
      dockerfile: config-server.Dockerfile
    container_name: config_server
    restart: on-failure
    hostname: config-server
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER_URL=${EUREKA_SERVER_URL}
    #    hostname: config_server
    ports:
      - ${CONFIG_SERVER_PORT}:8888
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 250M
          cpus: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api-gateway/default"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging: *logging
    depends_on:
      discovery:
        condition: service_healthy
        restart: true

  order_taking:
    build:
      context: ./order-taking
      dockerfile: order-taking.Dockerfile
    container_name: order_taking
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER_URL=${EUREKA_SERVER_URL}
        -DCONFIG_SERVER_URL=${CONFIG_SERVER_URL}
        -DKAFKA_URL=${KAFKA_URL}
        -Dserver.port=${ORDER_TAKING_PORT}
        -DPOSTGRES_APP_USER=${POSTGRES_APP_USER}
        -DPOSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
        -DPOSTGRES_APP_URL=${POSTGRES_APP_URL}
    ports:
      - ${ORDER_TAKING_PORT}:${ORDER_TAKING_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 200M
          cpus: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/main/test"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging: *logging
    depends_on:
      config_server:
        condition: service_healthy
        restart: true

  order_processing:
    build:
      context: ./order-processing
      dockerfile: order-processing.Dockerfile
    container_name: order_processing
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER_URL=${EUREKA_SERVER_URL}
        -DCONFIG_SERVER_URL=${CONFIG_SERVER_URL}
        -DKAFKA_URL=${KAFKA_URL}
        -Dserver.port=${ORDER_PROCESSING_PORT}
        -DPOSTGRES_APP_USER=${POSTGRES_APP_USER}
        -DPOSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
        -DPOSTGRES_APP_URL=${POSTGRES_APP_URL}
    ports:
      - ${ORDER_PROCESSING_PORT}:${ORDER_PROCESSING_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 200M
          cpus: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/main/test"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging: *logging
    depends_on:
      config_server:
        condition: service_healthy
        restart: true

  api_gateway:
    build:
      context: ./api-gateway
      dockerfile: api-gateway-server.Dockerfile
    container_name: api_gateway
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER_URL=${EUREKA_SERVER_URL}
        -DCONFIG_SERVER_URL=${CONFIG_SERVER_URL}
    ports:
      - ${API_GATEWAY_SERVER_PORT}:8765
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/main/test"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    logging: *logging
    depends_on:
      order_taking:
        condition: service_healthy
        restart: true
      order_processing:
        condition: service_healthy
        restart: true
