server.port: 8765

spring:
    application:
        name: api-gateway
    profiles:
        active: ${PROFILE:dev}
    config:
        import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

#spring.cloud.config.enabled: false
#spring.cloud.config.import-check.enabled: false
