server.port: 8765

spring:
    config.import: configserver:http://localhost:8888
    application.name: api-gateway

    cloud.gateway.discovery.locator:
        enabled: true
        lower-case-service-id: true

logging.pattern.console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
