server.port: 8765

spring:
    config.import: ${CONFIG_SERVER_URL:configserver:http://localhost:8888}
    application.name: api-gateway

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

spring.cloud.config.enabled: false
spring.cloud.config.import-check.enabled: false
