server.port: ${EUREKA_CLIENT_PORT:0}

spring:
    application:
        name: eclient
    profiles:
        active: micro
#    config.import: ${CONFIG_SERVER_URL:configserver:http://config-server:8888}
#    config.import: 'configserver:'

    cloud:
        config:
            fail-fast: true
            discovery:
                enabled: true
                service-id: CONFIGSERVER
            retry:
                initial-interval: 2000
                multiplier: 1.5
                max-interval: 60000
                max-attempts: 100
#        uri: http://config-server:8888
#        discovery.enabled: false
#        config.discovery.enabled: false
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
        fetch-registry: true
    instance:
        lease-renewal-interval-in-seconds: 10
