server.port: 0

spring:
    application:
        name: email-server
    profiles:
        active: ${PROFILE:micro,kafka}
    config:
        import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
    cloud:
        config:
            fail-fast: true
            discovery:
                enabled: true
                service-id: CONFIGSERVER
            retry:
                initial-interval: 2000
                multiplier: 1.5
                max-interval: 60000
                max-attempts: 100

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
        fetch-registry: true
    instance:
        lease-renewal-interval-in-seconds: 10
