server.port: 8888

spring:
    application:
        name: CONFIGSERVER

    cloud.config.server.git:
        uri: https://github.com/barracuda256/demo-order-taking-config.git
        clone-on-start: true
        basedir: file:./tmp/git-c
        default-label: main
        #For private repo
        # username: TODO
        # password: TODO

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    instance:
        instance-id: '${spring.application.name}:${random.uuid}'

logging.pattern.console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
