server.port: 8888

spring:
    application.name: github-config-server

    cloud.config.server.git:
        uri: https://github.com/barracuda256/demo-order-taking-config.git
        clone-on-start: true
        basedir: file:./tmp/git-c
        default-label: main
        #For private repo
        # username: TODO
        # password: TODO

logging.pattern.console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
