server.port: 8761

spring:
    application.name: eureka-server

logging:
    pattern.console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
    level.com.netflix:
        eureka: OFF
        discovery: OFF

eureka.client:
    register-with-eureka: false
    fetch-registry: false

