server.port: 8761

spring:
    config.import: configserver:http://localhost:8888
    application.name: eureka-server
#    application.name: eserver

eureka.client:
    register-with-eureka: false
    fetch-registry: false

logging.level.com.netflix:
    eureka: OFF
    discovery: OFF
